/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Subject as PrismaSubject,
  Exam as PrismaExam,
  VideoLesson as PrismaVideoLesson,
  Category as PrismaCategory,
} from "@prisma/client";

export class SubjectServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.SubjectCountArgs, "select">): Promise<number> {
    return this.prisma.subject.count(args);
  }

  async subjects<T extends Prisma.SubjectFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.SubjectFindManyArgs>
  ): Promise<PrismaSubject[]> {
    return this.prisma.subject.findMany<Prisma.SubjectFindManyArgs>(args);
  }
  async subject<T extends Prisma.SubjectFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.SubjectFindUniqueArgs>
  ): Promise<PrismaSubject | null> {
    return this.prisma.subject.findUnique(args);
  }
  async createSubject<T extends Prisma.SubjectCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SubjectCreateArgs>
  ): Promise<PrismaSubject> {
    return this.prisma.subject.create<T>(args);
  }
  async updateSubject<T extends Prisma.SubjectUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SubjectUpdateArgs>
  ): Promise<PrismaSubject> {
    return this.prisma.subject.update<T>(args);
  }
  async deleteSubject<T extends Prisma.SubjectDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.SubjectDeleteArgs>
  ): Promise<PrismaSubject> {
    return this.prisma.subject.delete(args);
  }

  async findExams(
    parentId: string,
    args: Prisma.ExamFindManyArgs
  ): Promise<PrismaExam[]> {
    return this.prisma.subject
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .exams(args);
  }

  async findVideoLessons(
    parentId: string,
    args: Prisma.VideoLessonFindManyArgs
  ): Promise<PrismaVideoLesson[]> {
    return this.prisma.subject
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .videoLessons(args);
  }

  async getCategory(parentId: string): Promise<PrismaCategory | null> {
    return this.prisma.subject
      .findUnique({
        where: { id: parentId },
      })
      .category();
  }
}
