/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { ExamListRelationFilter } from "../../exam/base/ExamListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { VideoLessonListRelationFilter } from "../../videoLesson/base/VideoLessonListRelationFilter";

@InputType()
class SubjectWhereInput {
  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ExamListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ExamListRelationFilter)
  @IsOptional()
  @Field(() => ExamListRelationFilter, {
    nullable: true,
  })
  exams?: ExamListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => VideoLessonListRelationFilter,
  })
  @ValidateNested()
  @Type(() => VideoLessonListRelationFilter)
  @IsOptional()
  @Field(() => VideoLessonListRelationFilter, {
    nullable: true,
  })
  videoLessons?: VideoLessonListRelationFilter;
}

export { SubjectWhereInput as SubjectWhereInput };
