/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VideoLessonService } from "../videoLesson.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VideoLessonCreateInput } from "./VideoLessonCreateInput";
import { VideoLesson } from "./VideoLesson";
import { VideoLessonFindManyArgs } from "./VideoLessonFindManyArgs";
import { VideoLessonWhereUniqueInput } from "./VideoLessonWhereUniqueInput";
import { VideoLessonUpdateInput } from "./VideoLessonUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VideoLessonControllerBase {
  constructor(
    protected readonly service: VideoLessonService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VideoLesson })
  @nestAccessControl.UseRoles({
    resource: "VideoLesson",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVideoLesson(
    @common.Body() data: VideoLessonCreateInput
  ): Promise<VideoLesson> {
    return await this.service.createVideoLesson({
      data: {
        ...data,

        subject: data.subject
          ? {
              connect: data.subject,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        id: true,

        subject: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
        videoUrl: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [VideoLesson] })
  @ApiNestedQuery(VideoLessonFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VideoLesson",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async videoLessons(@common.Req() request: Request): Promise<VideoLesson[]> {
    const args = plainToClass(VideoLessonFindManyArgs, request.query);
    return this.service.videoLessons({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,

        subject: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
        videoUrl: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VideoLesson })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoLesson",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async videoLesson(
    @common.Param() params: VideoLessonWhereUniqueInput
  ): Promise<VideoLesson | null> {
    const result = await this.service.videoLesson({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,

        subject: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
        videoUrl: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VideoLesson })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoLesson",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVideoLesson(
    @common.Param() params: VideoLessonWhereUniqueInput,
    @common.Body() data: VideoLessonUpdateInput
  ): Promise<VideoLesson | null> {
    try {
      return await this.service.updateVideoLesson({
        where: params,
        data: {
          ...data,

          subject: data.subject
            ? {
                connect: data.subject,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          id: true,

          subject: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
          videoUrl: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VideoLesson })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoLesson",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVideoLesson(
    @common.Param() params: VideoLessonWhereUniqueInput
  ): Promise<VideoLesson | null> {
    try {
      return await this.service.deleteVideoLesson({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,

          subject: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
          videoUrl: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
